name:                c0compiler
version:             0.1.0.0
github:              "githubuser/c0compiler"
license:             BSD3
author:              "Zhang Guyu"
maintainer:          "zhangguyu6@gmail.com"
copyright:           "2018 Zhang Guyu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/c0compiler#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >=3.1.10
- array >= 0.4 && < 0.6


library:
  source-dirs: 
    - src
  exposed-modules:
    - Frontend.Ast
    - Frontend.Token
    - Frontend.Lexer 
    - Frontend.Parser
    - Lib
  other-modules: 
  build-tools: alex


executables:
  c0compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c0compiler

tests:
  c0compiler-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - c0compiler
    - tasty 
    - tasty-hspec
    - hspec
